config/routes.rb
Agendo::Application.routes.draw do

  resources :pages
  resources :users
  resources :projects do 
    resources :needs  
  end
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout"  =>  "sessions#destroy", :as => :signout
  match "/auth/failure" => "sessions#failure"
  
  
  match "projects/:project_id/needs/:id/complete" => "needs#complete", :as => :complete_need
  
  root :to => "pages#home"

end

app/models/need.rb
class Need < ActiveRecord::Base

  belongs_to :project
  scope :completed, where(:completed => true)
  scope :incompleted, where(:completed => false)
  
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :needs
  validates :name, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["user_info"]["name"]
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  
  attr_accessor :description, :completed
  before_filter :get_project
  respond_to :html, :xml, :json
  
  def create
    @need = @project.needs.new(params[:id])
    if @need.save
      redirect_to project_path(@project), :notice => "Need created"
    else
      redirect_to project_path(@project), :error => "Something went wrong."
    end
  end
  
  def complete
    @need = @project.needs.find(params[:id])
    @need.completed = true
    @need.save
    redirect_to project_path(@project), :notice => "you completed a need!"
  end
  
  private
    def get_project
        @project = List.find(params[:project_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  respond_to :html, :xml, :json
  
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to projects_path, :notice => "Success!"
    else
      redirect_to new_project_path, :error => "Fail!"
    end
  end
  
  def show
    get_project
    @need = @project.needs.new
  end

  def edit
    get_project
  end
  
  def update
    get_project
    if @project.update_attributes(params[:project])
      redirect_to projects_path, :notice => "Project updated"
    else 
      redirect_to project_path(@project), :error => "Oops"
    end
  end
  
  def destroy
    get_project
    if @project.destroy
      redirect_to projects_path, :notice => "Project deleted"
    else
      redirect_to projects_path, :error => "Could not delete"
    end
  end
  
  private
    def get_project
      @project = Project.find(params[:id])
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out"
  end

  def failure
    session[:user_id] = nil
    redirect_to root_url, :error => "Sign in didn't work."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agendo | Help others help you</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link rel="icon" href="/images/favicon.ico" type="image/x-icon" /> 
  <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
</head>
<body>
<div id="header">
    <div id="sign_in">
        <% if current_user %>
            Welcome <%= current_user.name %>
            <%= link_to "Sign Out", signout_path %>
        <% else %>
            <%= link_to "Sign in with Twitter", "/auth/twitter" %>
            <%= link_to "Sign in with Facebook", "/auth/facebook" %>
        <% end %>
    </div>

</div>
<div id="flash">
    <% unless flash.blank? %>
        <div id="messages">
            <% flash.each do |key, msg| %>
                <%= content_tag(:div, msg, :class => "#{key} message", :id => "#{key}_message") %>
            <% end %>
        </div>
    <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<%= image_tag('logo.gif') %>

app/views/projects/_form.html.erb
<%= form_for @project do |form| %>
    <label>Name:
        <p><%= form.text_field :name %></p>
    </label>
    <label>Description:
        <p><%= form.text_field :description %></p>
    </label>
    <p><%= form.submit %></p>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit this project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>What I'm trying to get done</h1>

<% @projects.each do |project| %>
    <h2><%= link_to(project.name, project_path(project)) %></h2>
    <p>
        <%= project.description %> - 
        <%= link_to "Edit", edit_project_url(project) %> | 
        <%= link_to "Delete", project_url(project), :method => :delete %>
        </p>
<% end %>

<hr />

<%= link_to "Add new project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p><%= @project.description %></p>

<ul>
    <% @project.needs.each do |need| %>
        <% if need.completed %>
            <li><%= need.description %> - DONE</li>
        <% else %>
            <li><%= need.description %> - <%= button_to "Complete", complete_need_path(@project.id, need.id) %></li>
        <% end %>
    <% end %>
</ul>

<%= form_for [@project, @need] do |form| %>
    <p><%= form.text_field :description %> <%= form.submit %></p>
<% end %>
<h2 />
<%= link_to "Home", projects_path %>